version: "3"

services:
  oj.main:
    build:
      context: .
      dockerfile: Dockerfile
    image: namofun/on-premise:latest
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      #For HTTPS:
      #- ASPNETCORE_URLS=http://0.0.0.0:80;https://0.0.0.0:443
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/namomo-test.pfx
      #- ConnectionStrings__PdfService=http://alvarcarto.url-to-pdf-api.service/api/render
      - ConnectionStrings__ContestKeyword=GenerateYourself
      - ConnectionStrings__SqlServerDbConnection=Server=tcp:sql.data,1433;Initial Catalog=jop;Persist Security Info=False;User ID=SA;Password=Passw0rd;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;
      - Mailing__Sender=Judge On Premise
      - Mailing__User=admin@admin.com
      - Mailing__Key=gocreateyourself
      - Mailing__Server=smtp.qq.com
      - Mailing__Port=587
      - TZ=Asia/Shanghai
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - /data/namofun/on-premise-sqlservr/https:/https:ro
      - /data/namofun/on-premise-sqlservr/runs:/app/Runs
      - /data/namofun/on-premise-sqlservr/problems:/app/Problems
      - /data/namofun/on-premise-sqlservr/job-blobs:/app/JobBlobs
      - /data/namofun/on-premise-sqlservr/images/problem:/app/wwwroot/images/problem
      - /data/namofun/on-premise-sqlservr/images/affiliations:/app/wwwroot/images/affiliations
      - /data/namofun/on-premise-sqlservr/keys:/root/.aspnet/DataProtection-Keys
    depends_on:
      - sql.data

  sql.data:
    image: mcr.microsoft.com/mssql/server:2019-CU10-ubuntu-18.04
    environment:
      - MSSQL_SA_PASSWORD=Passw0rd
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - TZ=Asia/Shanghai
    volumes:
      - /data/namofun/on-premise-sqlservr/database/data:/var/opt/mssql/data
      - /data/namofun/on-premise-sqlservr/database/log:/var/opt/mssql/log
      - /data/namofun/on-premise-sqlservr/database/secrets:/var/opt/mssql/secrets
    ports:
      - "1433:1433"
    user: root
